Table user {
   _id objectId [not null,unique]
  club objectId [default:null,ref: - club._id]
  public_id varchar [not null,unique]

  fullname varchar [not null]
  mail mail [not null,unique]
  mail_confirmed boolean [default: false]
  password varchar [not null]
  phone long [not null,unique]
  picture picture
  user_type userType 


}

Table club {
 _id objectId [not null,unique]
  name varchar [not null,unique]
  description text [not null]
  picture picture
  
  president objectId [ref: - user._id]
  vicePresident objectId [ref: - user._id]
  accountant objectId [ref: - user._id]
  advisor objectId [ref: - user._id]
  
  past_administration administration_year [ref: < administration_year.year]
  communities varchar [pk]
  
  
  events event [ref: < event._id]
  documents document [ref: < document._id]

 }
Table administration_year {
  year datetime
  president objectId
  vice_president objectId
  accountant objectId
}
Table event{
  _id objectId
  name varchar
  description text
  picture picture
  status fileStatus
  startDate datetime
  endDate datetime
  eventType eventType
  departments department [pk]
  location varchar [pk] 
  speakers varchar [pk]
  companies varchar [pk]
  supporterClubs objectId [pk, ref:< club._id]
  consultant objectId [ref: - user._id]
  reporesenter objectId [ref: - user._id]

 
}

Table document{
  _id objectId
  name varchar
  description text
  status fileStatus
  date datetime
  departments department [pk]
  file file [pk]
    
}
Table chat{
  users objectId [pk,ref: < user._id]
  messageList message [pk,ref: < message._id] 
    
}
Table message{
  _id objectId 
  message text
  content file
  date datetime  [default: `now()`]
 
}
Enum fileStatus{
  draft
  requested 
  created
  awaiting
  accepted
  rejected
  completed
}
Enum eventType{
    Seminar 
    Conference 
    Festival
    Contest
    Movie_Screening
    Education 
    Exhibition 
    Stand 
    Club_Meeting
    Workshop
    Other
}
Enum userType{
  visitor
  president [note:"club_admin"]
  vice_resident [note:"club_admin"]
  accountant [note:"club_admin"]
  advisor
  department
  administrator
}

